# -*- coding: utf-8 -*-
"""B00-restAPI_exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jUIAahFD9YWjVKwRmP3jm5uDIPLuBoyM

### Tugas GET API dari Mas Kal
Buat program Python untuk konversi mata uang ke dan/atau dari Rupiah:

Inputan:
- Masukkan Nama Bank
- Menu Opsi:
  1. IDR to mata uang asing
    - Masukkan mata uang asing: USD/JPY/GBP/dll
    - Masukkan nilai Rupiah : 50000
    - Outputnya: "Nilai uang anda ... Rupiah dalam ... (mata uang asing) adalah ... ...(konversi ke mata uang asing).
  2. mata uang asing to IDR
    - masukkan mata uang asing : USD/JPY/GBP
    - masukkan nilai uang anda : 50000
    - outputnya: "Nilai uang anda ... (mata uang asing) dalam Rupiah adalah ... ... (konversi ke Rupiah).

Deadline malam

kirim ke email mas Kal

## IDR to Others
"""

# IDR to others
import requests
from bs4 import BeautifulSoup

bank = input("Masukkan nama Bank yang Anda inginkan (MANDIRI/BCA/COMMONWEALTH/BRI/dll): ").upper()
# Bank List on Web Page
url_bank = f"https://kurs.web.id"
web_bank = requests.get(url_bank)
output_bank = BeautifulSoup(web_bank.content, "html.parser")
bank_list = []
for name in output_bank.find_all('ul', class_ = "menu-list"):
  bank_list = name.text.split()

if bank in bank_list:
  # Currency List on Web Page
  url_curr = f"https://kurs.web.id/bank/{bank.lower()}"
  web_curr = requests.get(url_curr)
  output_curr = BeautifulSoup(web_curr.content, "html.parser")
  currency_list = []
  for curr in output_curr.find_all('abbr'):
    currency_list.append(curr.text[1:4])

  # Converting IDR to Other Currency
  currency = input("Masukkan mata uang asing yang Anda inginkan (USD/JPY/SGD/dll): ").upper()
  if currency.isalpha() and currency in currency_list:
    value = int(input(f"Masukkan nilai Rupiah Anda (hanya angka): "))
    token = "1ERfG9RP5ZiaKsyPzHQQIENwXKsd7Vz7zBDCq6qz"

    url = f"https://api.kurs.web.id/api/v1?token={token}&bank={bank.lower()}&matauang={currency.lower()}"
    data = requests.get(url)
    output = data.json()
    # print(output)
    kurs_jual = output['jual']
    # print(kurs_jual)
    converted = value / kurs_jual
    # print(converted)
    print(f"Nilai uang Anda {value} Rupiah dalam {currency} adalah {converted:.2f} {currency}.")
  else:
    print("Sorry, please try another currency!")
else:
  print("Sorry, please try another bank!")

"""## Others to IDR"""

# Others to IDR
import requests
from bs4 import BeautifulSoup

bank = input("Masukkan nama Bank yang Anda inginkan (MANDIRI/BCA/COMMONWEALTH/BRI/dll): ").upper()
# Bank List on Web Page
url_bank = f"https://kurs.web.id"
web_bank = requests.get(url_bank)
output_bank = BeautifulSoup(web_bank.content, "html.parser")
bank_list = []
for name in output_bank.find_all('ul', class_ = "menu-list"):
  bank_list = name.text.split()

if bank in bank_list:
  # Currency List on Web Page
  url_curr = f"https://kurs.web.id/bank/{bank.lower()}"
  web_curr = requests.get(url_curr)
  output_curr = BeautifulSoup(web_curr.content, "html.parser")

  currency_list = []
  for curr in output_curr.find_all('abbr'):
    currency_list.append(curr.text[1:4])

  # Converting Process from Other Currency to IDR
  currency = input("Masukkan mata uang asing yang Anda gunakan (USD/JPY/SGD/dll): ").upper()
  if currency.isalpha() and currency in currency_list:
    value = int(input(f"Masukkan nilai {currency} Anda (hanya angka): "))
    token = "1ERfG9RP5ZiaKsyPzHQQIENwXKsd7Vz7zBDCq6qz"

    url = f"https://api.kurs.web.id/api/v1?token={token}&bank={bank.lower()}&matauang={currency.lower()}"
    data = requests.get(url)
    output = data.json()

    kurs_beli = output['beli']
    converted = value * kurs_beli

    print(f"Nilai uang Anda {value} {currency} dalam Rupiah adalah {converted:.2f} Rupiah.")
  else:
    print("Sorry, please try another currency!")
else:
  print("Sorry, please try another bank!")

